name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: debian:bookworm-slim
    steps:
      - name: Install prerequisites
        run: apt-get update && apt-get install -y curl git zsh

      - uses: actions/checkout@v6

      - name: Run install script
        run: bash install.sh
